# Site wide configuration

title:            Software Blog
locale:           en_US
url: http://sobkowiak.github.io/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Krzysztof Sobkowiak
  avatar: ksobkowiak-photo.jpg
  bio: "JEE & OSS Solutions Architect, Apache Software Foundation Member, Apache ServiceMix Committer & PMC Member, Senior Solution Architect @ Capgemini"
  email:
  disqus-shortname: sobkowiakgithubio
  twitter: ksobkowiak
  facebook: #sobkowiak.krzysztof 
  google:
    plus: KrzysztofSobkowiak
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sobkowiak
  stackoverflow: 1152790/ksobkowiak
  linkedin: krzysztofsobkowiak
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
